### ISSUE TITLE
What is the futures-rustls crate?

### ISSUE THREAD

**Issue by tomaka** [quininer/tokio-rustls#51]
The `futures-rustls` crate on crates.io redirects here, but this is obviously `tokio-rustls`.
Could you clarify what `futures-rustls` is? Is it maintained? Abandoned? Some weird crate-alias thing?

I'm opening this issue because it would be great to publish a new version of `futures-rustls`. The current one indirectly uses an old version of `ring`, which conflicts with the version of `ring` used bvy most of the ecosystem.

Thank you!

**Comment by quininer** [comment]
A short answer, `futures-rustls` crate is in the [futures-rustls](https://github.com/quininer/tokio-rustls/tree/futures-rustls) branch.

I originally thought we would move to `futurse-io` (see #31), but now the ecosystem has split, and `tokio-io` and `futures-io` define different trait. So I split this crate into two libraries, `futures-rustls` and `tokio-rustls`, and look forward to deprecating one of them in the future. (see #41)

For a while, the [tokio-0.2](https://github.com/quininer/tokio-rustls/tree/tokio-0.2) branch had better maintenance due to community contributions. (see #43 #45 #48 #49) and recently the `async-std` team has forked the [futures-rustls](https://github.com/async-rs/async-tls) branch. This repo may focus on `tokio`.

**Comment by quininer** [comment]
I just released a new version of [futures-rustls](https://crates.io/crates/futures-rustls/0.12.0-alpha.2).
